### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by Hjequier** [btozer/gmg#9]
Hello, i was trying to install your gmg library software. I follow your guide in https://btozer.github.io/gmg/html/installation.html, but i´m getting this error.
![gmg-error](https://github.com/btozer/gmg/assets/124008684/b54eab47-dc11-4005-afa4-ddf65ac2d155)
I tried in both, Windows 10 (image) and Ubuntu 23, and have the same exact issue.
Just for letting u know i downloaded last version on ur github. (here is the dir /gmg)

![dir](https://github.com/btozer/gmg/assets/124008684/e6cf3ec7-7023-4f9d-aaa9-ad3869b6ceb0)

Seems a very good project, with nice GUI. 
I was looking if i can use it in a real project to model gravity data in the Altiplano-Puna, Chile.

**Comment by btozer** [comment]
Hi @Hjequier, I'm currently working on packaging this project for pip and conda-forge to streamline the installation. 

You could try installing via:

pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple gmgpy

Then, you should be able to load gmg via: gmgpy on the command line 

Although installing via pip may lead to dependancy conflicts. I have tested the test.pypi  install on macOS windows 11 and ubuntu 22.04. 

I have not uploaded to conda-forge yet, but you may wish to wait for that and create a dedicated env.

**Comment by Hjequier** [comment]
Thank you, i successfully installed it in windows 10 and Ubuntu 23.
